/*
 * StandOrt — Seed-Daten (migriert aus studio_arno_vertrieb-7.html)
 *
 * Diese Einträge werden im Demo-Modus als Startdatensatz verwendet und dienen
 * als Quelle für db/seed.sql. Jeder Eintrag hat eine feste UUID (id) und einen
 * stabilen slug, damit Inserts idempotent bleiben.
 *
 * Reklassifizierung: offensichtliche Fachmessen wurden von "sonstiges" auf
 * "messe" umgestellt (Blickfang, Bisutex, Révélations, WSN). Alles andere bleibt.
 *
 * Feldmodell entspricht der Tabelle "entries":
 *   category: 'festival' | 'markt' | 'messe' | 'sonstiges'
 *   status:   'offen' | 'beworben' | 'wartet' | 'zugesagt' | 'abgesagt'
 */
(function () {
  var STANDORT_SEED = [
  { id: "56a5d5e2-0f2d-5621-9b98-c37c71c534c7", slug: "blickfang-zh", name: "Blickfang Design Messe", category: "messe", city: "Zürich", country: "Schweiz", lat: 47.3769, lng: 8.5417, dates_text: "20.–22. November 2026", event_start: "2026-11-20", event_end: "2026-11-22", deadline: "2026-10-20", deadline_text: "", status: "offen", link: "https://blickfang.com/wp-content/uploads/BLICKFANG-Ausstellermappe.pdf", contact: "", note: "", cost: "", archived: false },
  { id: "e01ed160-0859-563b-8b6e-0a3aa1ac425d", slug: "blickfang-s", name: "Blickfang Design Messe", category: "messe", city: "Stuttgart", country: "Deutschland", lat: 48.7758, lng: 9.1829, dates_text: "12.–14. März 2027", event_start: "2027-03-12", event_end: "2027-03-14", deadline: "2026-10-20", deadline_text: "", status: "offen", link: "https://blickfang.com/wp-content/uploads/BLICKFANG-Ausstellermappe.pdf", contact: "", note: "", cost: "", archived: false },
  { id: "c7bfd65f-f270-5c93-a1e0-fc823e878627", slug: "blickfang-b", name: "Blickfang Design Messe", category: "messe", city: "Basel", country: "Schweiz", lat: 47.5596, lng: 7.5886, dates_text: "19.–21. März 2027", event_start: "2027-03-19", event_end: "2027-03-21", deadline: "2026-10-20", deadline_text: "", status: "offen", link: "https://blickfang.com/wp-content/uploads/BLICKFANG-Ausstellermappe.pdf", contact: "", note: "", cost: "", archived: false },
  { id: "582190ed-ba76-5344-9776-02115d567c2b", slug: "blickfang-h", name: "Blickfang Design Messe", category: "messe", city: "Hamburg", country: "Deutschland", lat: 53.5511, lng: 9.9937, dates_text: "1.–3. Oktober", event_start: null, event_end: null, deadline: null, deadline_text: "noch offen", status: "offen", link: "https://blickfang.com/wp-content/uploads/BLICKFANG-Ausstellermappe.pdf", contact: "", note: "", cost: "", archived: false },
  { id: "f974bd91-ed6c-5a4d-a0b6-37013b0bacbb", slug: "formszene", name: "FORMSZENE Design und Kunsthandwerk", category: "markt", city: "Winterthur", country: "Schweiz", lat: 47.5001, lng: 8.7241, dates_text: "März 2027", event_start: null, event_end: null, deadline: null, deadline_text: "offen, ab August 2026", status: "offen", link: "https://www.formszene.ch/mitmachen/", contact: "", note: "", cost: "", archived: false },
  { id: "c7aef078-a1a8-5a1c-b64c-4b35657d4de6", slug: "naturklang", name: "Naturklang", category: "festival", city: "Zürich", country: "Schweiz", lat: 47.3769, lng: 8.5417, dates_text: "Random", event_start: null, event_end: null, deadline: null, deadline_text: "keine, laufende Bewerbung", status: "offen", link: "", contact: "info@naturklang.ch", note: "", cost: "", archived: false },
  { id: "63748209-8d07-5817-92d7-f16f843c68eb", slug: "laluna", name: "La Luna Yogafestival", category: "festival", city: "Sempachersee", country: "Schweiz", lat: 47.1333, lng: 8.15, dates_text: "21.–23. Mai 2027", event_start: "2027-05-21", event_end: "2027-05-23", deadline: null, deadline_text: "offen", status: "offen", link: "https://www.laluna-yogafestival.ch", contact: "Ronald Kalbermatten, infrastruktur@laluna-yogafestival.ch", note: "", cost: "", archived: false },
  { id: "8ddf53e7-50dd-55ff-ad0a-43657d5b19f7", slug: "burningmountain", name: "Burning Mountain", category: "festival", city: "Zernez", country: "Schweiz", lat: 46.6944, lng: 10.0989, dates_text: "24.–27. Juni 2027", event_start: "2027-06-24", event_end: "2027-06-27", deadline: null, deadline_text: "offen", status: "offen", link: "", contact: "", note: "", cost: "", archived: false },
  { id: "d593ca25-7011-561b-a01e-5ff44897039f", slug: "mystica", name: "Mystica Daydance", category: "festival", city: "Zürich", country: "Schweiz", lat: 47.3769, lng: 8.5417, dates_text: "6. März 2027", event_start: "2027-03-06", event_end: "2027-03-06", deadline: null, deadline_text: "offen", status: "offen", link: "", contact: "muestik@gmail.com", note: "", cost: "", archived: false },
  { id: "f08c95d3-84b7-5af7-b365-adfccae668c4", slug: "paleo", name: "Paleo Festival", category: "festival", city: "Nyon", country: "Schweiz", lat: 46.3833, lng: 6.2333, dates_text: "Ende Juli 2027", event_start: null, event_end: null, deadline: "2027-01-15", deadline_text: "November 2026 – ca. Mitte Januar 2027", status: "offen", link: "https://yeah.paleo.ch/de/node/67", contact: "", note: "", cost: "", archived: false },
  { id: "8df2cb08-cfb8-5dca-b479-13729230e2f8", slug: "onelove", name: "One Love Festival", category: "festival", city: "Graubünden", country: "Schweiz", lat: 46.8, lng: 9.6, dates_text: "letztes August-Wochenende 2027", event_start: null, event_end: null, deadline: null, deadline_text: "Start ca. März/April 2027", status: "offen", link: "https://onelovefestival.ch/contact/", contact: "", note: "", cost: "", archived: false },
  { id: "f54dd7c2-c620-58fe-bdf9-aff211bc1604", slug: "shankra", name: "Shankra", category: "festival", city: "Lostallo", country: "Schweiz", lat: 46.3833, lng: 9.2667, dates_text: "ca. Anfang–Mitte Juli 2027", event_start: null, event_end: null, deadline: "2026-11-01", deadline_text: "ca. November 2026", status: "offen", link: "https://shankrafestival.org/de/switzerland/participate/market-application", contact: "", note: "2026 zum 3. Mal in Folge abgesagt, Comeback unsicher", cost: "", archived: false },
  { id: "f2ee747c-3de1-54c8-8fa4-6db94b513d8c", slug: "wm-bremgarten", name: "Weihnachtsmarkt Bremgarten", category: "markt", city: "Bremgarten", country: "Schweiz", lat: 47.35, lng: 8.3333, dates_text: "3.–6. Dezember 2026", event_start: "2026-12-03", event_end: "2026-12-06", deadline: "2026-08-17", deadline_text: "", status: "offen", link: "https://www.bremgarten.ch/online-schalter/20339/detail", contact: "", note: "Herbstmarkt 10.8.2026, Oster-/Pfingstmarkt 25.1.2027", cost: "", archived: false },
  { id: "8d11ca2a-d2c5-533a-90bc-345d704645e3", slug: "wm-basel", name: "Weihnachtsmarkt Basel", category: "markt", city: "Basel", country: "Schweiz", lat: 47.5596, lng: 7.5886, dates_text: "19. Dezember 2026", event_start: "2026-12-19", event_end: "2026-12-19", deadline: "2026-09-30", deadline_text: "", status: "offen", link: "https://docs.google.com/forms/d/e/1FAIpQLSexL9AOucRsRBnmR50_6IflSZO7_4FTSFa05MOTxEjrjpc3ow/viewform", contact: "", note: "", cost: "", archived: false },
  { id: "4fd33ca8-8331-5637-a9b0-5915753bdebf", slug: "wm-strasbourg", name: "Weihnachtsmarkt Strasbourg", category: "markt", city: "Strasbourg", country: "Frankreich", lat: 48.5734, lng: 7.7521, dates_text: "Dezember 2027", event_start: null, event_end: null, deadline: null, deadline_text: "Start ca. 1. April 2027", status: "offen", link: "https://www.strasbourg.eu/chalet-marche-noel", contact: "", note: "", cost: "", archived: false },
  { id: "69e317e9-0674-52c9-9b8b-08ae2b422ad0", slug: "wm-colmar", name: "Weihnachtsmärkte Colmar, Eguisheim, Münster etc.", category: "markt", city: "Elsass", country: "Frankreich", lat: 48.0794, lng: 7.3585, dates_text: "Dezember 2027", event_start: null, event_end: null, deadline: null, deadline_text: "Start ca. März – April 2027", status: "offen", link: "https://www.noel-colmar.com/de/", contact: "", note: "", cost: "", archived: false },
  { id: "faa7184f-791b-5157-ab45-d26f156d69ee", slug: "voov", name: "VooV Festival", category: "festival", city: "Putlitz, Brandenburg", country: "Deutschland", lat: 53.2333, lng: 12.05, dates_text: "voraussichtlich 16.–19. Juli 2027", event_start: null, event_end: null, deadline: null, deadline_text: "Start ca. Januar / Februar 2027", status: "offen", link: "https://www.voov-festival.de/contact", contact: "", note: "", cost: "", archived: false },
  { id: "822a3c02-b3eb-5e57-9e9f-b09e1e7e9894", slug: "feel", name: "Feel Festival", category: "festival", city: "Bergheider See, Brandenburg", country: "Deutschland", lat: 51.62, lng: 13.8, dates_text: "voraussichtlich Mitte Juli 2027", event_start: null, event_end: null, deadline: null, deadline_text: "Start ca. November 2026", status: "offen", link: "https://feel-festival.de/kontakt", contact: "", note: "", cost: "", archived: false },
  { id: "75fd883c-d7fb-504b-9e85-847ec8992322", slug: "antaris", name: "Antaris Project Festival", category: "festival", city: "Stölln/Gollenberg, Havelland", country: "Deutschland", lat: 52.75, lng: 12.35, dates_text: "Mitte Juli 2027 (evtl. fällt aus)", event_start: null, event_end: null, deadline: null, deadline_text: "offen", status: "offen", link: "", contact: "shops@antaris-project.de", note: "2025 + 2026 pausiert, Comeback 2027 angekündigt", cost: "", archived: false },
  { id: "94f4e44f-7956-5c46-a837-c0ada0205792", slug: "boheme", name: "Bohème Fest' – Marché du Lez", category: "markt", city: "Montpellier", country: "Frankreich", lat: 43.6109, lng: 3.8772, dates_text: "Mitte Juni 2027", event_start: null, event_end: null, deadline: null, deadline_text: "laufend offen, je früher desto besser", status: "offen", link: "https://synerg-in.com/projet-evenementiel/boheme-fest-montpellier/", contact: "", note: "", cost: "", archived: false },
  { id: "a36a384b-52f4-5626-af49-eb6eebf39313", slug: "revelations", name: "Révélations – Biennale internationale métiers d'art (B2B)", category: "messe", city: "Paris", country: "Frankreich", lat: 48.8661, lng: 2.3125, dates_text: "19.–23. Mai 2027", event_start: "2027-05-19", event_end: "2027-05-23", deadline: "2026-09-27", deadline_text: "2. Bewerbungsphase", status: "offen", link: "https://www.revelations-grandpalais.com/en/exhibit/", contact: "", note: "Sichtbarkeit, Direktverkauf an Sammler, Galerie-Kontakte — eher Konsignation als Wholesale, bizli en stretch aber who knows", cost: "", archived: false },
  { id: "3972f79b-c434-5f40-8529-673295df50cd", slug: "wsn", name: "Multiple Exhibitions (B2B context, WSN)", category: "messe", city: "Paris", country: "Frankreich", lat: 48.8566, lng: 2.3522, dates_text: "September 2026 – März 2027", event_start: null, event_end: null, deadline: null, deadline_text: "laufend", status: "offen", link: "https://wsn-events.com/en/exposer", contact: "", note: "Registrierung: https://wsn.community/en/pro/first-registration", cost: "", archived: false },
  { id: "2c31acf2-c7ea-5a46-997b-d8db6f24c6b2", slug: "hadra", name: "Hadra Trance Festival", category: "festival", city: "Vieure, Allier", country: "Frankreich", lat: 46.4667, lng: 2.8833, dates_text: "Ende August 2027", event_start: null, event_end: null, deadline: "2027-03-01", deadline_text: "Januar – März 2027", status: "offen", link: "", contact: "stands@hadra.net", note: "", cost: "", archived: false },
  { id: "309e8c4e-b57d-5e32-bd3d-eebfc0620756", slug: "rototom", name: "Rototom Sunsplash Festival", category: "festival", city: "Benicàssim, Valencia", country: "Spanien", lat: 40.05, lng: 0.0667, dates_text: "Mitte August 2027", event_start: null, event_end: null, deadline: "2027-02-01", deadline_text: "so früh wie möglich – Februar 2027", status: "offen", link: "https://hello.rototom.com/portal/en/kb/articles/commercial-proposal", contact: "", note: "Mercado ArteSano (Kunsthandwerk) vs. Mercado (allgemein, Bisutería) unterscheiden", cost: "", archived: false },
  { id: "2b6c9e55-d14b-534f-9aa6-9c478d39e839", slug: "palo", name: "Palo Market Fest", category: "markt", city: "Poblenou, Barcelona", country: "Spanien", lat: 41.3989, lng: 2.1994, dates_text: "monatlich, jedes erste Wochenende", event_start: null, event_end: null, deadline: null, deadline_text: "laufend, monatlich", status: "offen", link: "https://palomarketfest.com/en/exhibitors", contact: "", note: "", cost: "", archived: false },
  { id: "570bb13a-3db6-5e8b-b75c-39fcce19a33b", slug: "festivalet", name: "Festivalet Markt", category: "markt", city: "Fabra i Coats, Barcelona", country: "Spanien", lat: 41.4145, lng: 2.1936, dates_text: "12.–13. Dezember 2026", event_start: "2026-12-12", event_end: "2026-12-13", deadline: null, deadline_text: "startet 1. September", status: "offen", link: "https://www.festivalet.com/contact", contact: "", note: "", cost: "", archived: false },
  { id: "a096e68a-54cf-557b-8e7e-a6b9537569e1", slug: "bisutex", name: "Bisutex Messe", category: "messe", city: "Madrid", country: "Spanien", lat: 40.4168, lng: -3.7038, dates_text: "24.–27. September", event_start: null, event_end: null, deadline: null, deadline_text: "so schnell wie möglich", status: "offen", link: "https://www.ifema.es/en/bisutex/exhibitors", contact: "", note: "Talents-Wettbewerb (kostenlos) hat eigene Frist, separat prüfen", cost: "", archived: false },
  { id: "3d490ba6-cfe0-503b-b1f2-a20142814b44", slug: "boom", name: "Boom Festival", category: "festival", city: "Idanha-a-Nova", country: "Portugal", lat: 40.0167, lng: -7.2333, dates_text: "18.–25. Juli 2027", event_start: "2027-07-18", event_end: "2027-07-25", deadline: null, deadline_text: "offen (Website noch nicht aktualisiert)", status: "offen", link: "https://www.boomfestival.org/participate/fleamarket", contact: "", note: "Biennale, 30. Jubiläum", cost: "", archived: false },
  { id: "c5adefb2-5ec7-57ef-b3ad-38b28f251f38", slug: "fatacil", name: "FATACIL Lagoa Festival", category: "festival", city: "Lagoa, Algarve", country: "Portugal", lat: 37.1333, lng: -8.4667, dates_text: "Ende August 2027", event_start: null, event_end: null, deadline: "2027-03-01", deadline_text: "März 2027", status: "offen", link: "https://www.fatacil.pt/pages/16", contact: "", note: "", cost: "", archived: false },
  { id: "98b08f19-ce98-5c2d-9c80-4c2e9e7ccbbb", slug: "hype", name: "Hype Market", category: "markt", city: "Alvalade, Lissabon", country: "Portugal", lat: 38.75, lng: -9.15, dates_text: "monatlich (Termin TBD)", event_start: null, event_end: null, deadline: null, deadline_text: "noch offen", status: "offen", link: "", contact: "", note: "", cost: "", archived: false }
  ];

  // Im Browser als globale Seed-Quelle, unter Node als CommonJS-Export
  // (Quelle für db/seed.sql). window wird erst NACH der Guard angefasst.
  if (typeof window !== "undefined") { window.STANDORT_SEED = STANDORT_SEED; }
  if (typeof module !== "undefined" && module.exports) { module.exports = STANDORT_SEED; }
})();
